### ISSUE TITLE
Dynamically change language by using Blade syntax

### ISSUE THREAD

**Issue by pvetal** [ARCANEDEV/noCAPTCHA#105]
- noCaptcha Version: ^12.2
- Laravel Version: 8.52
- PHP Version: ^7.3

### Description: Hi. I try to use this package for multi language project. Tell me please, can I dynamically change language by using Blade syntax?
Maybe for example some like:

{!! Form::open([...]) !!}
    // Other inputs...
    {!! no_captcha()->display(**['lang'=>'en']**) !!}
    {!! Form::submit('Submit') !!}
{!! Form::close() !!}

// Remember what your mother told you
{!! no_captcha()->script() !!}

Thanks ))

**Comment by arcanedev-maroc** [comment]
Have you tried using the `no_captcha()->setLang()` method ? something like that:

```blade
{{ no_captcha()->setLang('en')->display() }}
```
