### ISSUE TITLE
No scriptWithCallback() output in Laravel 5.2

### ISSUE THREAD

**Issue by ivanvermeyen** [ARCANEDEV/noCAPTCHA#38]
# Hi,

I'm a bit clueless about this one...
I have a page (Laravel 5.2 blade file) with 2 forms.
Each form successfully renders a captcha `div`:

``` php
{!! Captcha::display('captcha1', ['data-theme' => 'dark']) !!}
{!! Captcha::display('captcha2', ['data-theme' => 'dark']) !!}
```

This results in:

``` html
<div class="g-recaptcha" data-sitekey="XXXX" id="captcha1" name="captcha1" data-theme="dark"></div>
```

But at the bottom of the page, the script doesn't get echo'd out:

``` php
{!! Captcha::scriptWithCallback(['captcha1', 'captcha2']) !!}
```

However, when I call this method with `php artisan tinker`, I do get the following output:

```
>>> Captcha::scriptWithCallback(['captcha1', 'captcha2']);
=> """
   <script>\n
   var captchaRenderCallback = function() {\n
   if (document.getElementById('captcha1')) { grecaptcha.render('captcha1', {'sitekey' : 'XXXX'}); }\n
   if (document.getElementById('captcha2')) { grecaptcha.render('captcha2', {'sitekey' : 'XXXX'}); }\n
   };\n
   </script>\n
   <script src="https://www.google.com/recaptcha/api.js?hl=nl&onload=captchaRenderCallback&render=explicit" async defer></script>
   """
>>>
```

If I paste this script on the page, the captchas work (although they don't have the dark theme).

Do you have any ideas why I'm not getting any output?

**Comment by arcanedev-maroc** [comment]
OK, i'm going to test your case and see what's the issue.

**Note :** Each form must have one captcha (not both of them).

**Comment by ivanvermeyen** [comment]
Thanks!
To confirm, I have 1 form with captcha1 and another form with captcha2. I will also try it in a fresh project tomorrow.

**Comment by ivanvermeyen** [comment]
Hi,

I have tried it in a fresh project and it worked perfectly... so I started to try and disable some middleware etc... and there seems to be some sort of conflict with the `\GeneaLabs\LaravelCaffeine\Http\Middleware\LaravelCaffeineDripMiddleware::class,` middleware.
When I disable it, everything works.

I haven't dug deeper into this, but I wanted to let you know, so you're not chasing ghosts.

One thing I also need to figure out is how to get the dark theme back ;)

**Comment by ivanvermeyen** [comment]
This is so weird... if I open your class and I edit the `scriptWithCallback` method like this:

```
return '<script>alert("hello");</script>';
```

Then the javascript gets printed and the alert shows...
But when your `$script` variable is returned, there is no `<script>` in the source.
And `$script` does have the correct value when I `dd()` it.

What `LaravelCaffeineDrip` seems to do is render the view and replace the closing `</body>` tag with a `<script>` and the closing `</body>` tag...

https://github.com/GeneaLabs/laravel-caffeine/blob/master/src/Http/Middleware/LaravelCaffeineDripMiddleware.php#L24-L41

If I die&dump the rendered view in their middleware:

```
if (method_exists($content, 'render')) {
    $content = $content->render();
}
dd($content);
```

My test alert script is in it, but your script is not...

**Comment by arcanedev-maroc** [comment]
I think the issue is related to this https://github.com/GeneaLabs/laravel-caffeine/issues/7.

The `script` method must be called once, if it's called more than once, the return value is gonna be empty.
