### ISSUE TITLE
Use accepted instead of required at the validation

### ISSUE THREAD

**Issue by mpathy** [ARCANEDEV/noCAPTCHA#40]
It is a box to click in, you confirm you are no robot. 
So the require validator is a bit misleading - especially at the translations of the validation file.

Other please add a description how to make a custom require only displayed for Captchas.

**Comment by arcanedev-maroc** [comment]
The [accepted](https://laravel.com/docs/5.3/validation#rule-accepted) rule is not the same as the [required](https://laravel.com/docs/5.3/validation#rule-required).

You need to verify on your server side the **code that google generate** on client side. This is not a value like `yes, on, 1, or true`.

You can customize your captcha error message by adding a third parameter in your `Validation::make($data, $rules, $messages)`.

Check this for more details: https://laravel.com/docs/5.3/validation#working-with-error-messages

**UPDATE:** You can find a description about the `custom` messages in [Laravel Usage section](https://github.com/ARCANEDEV/noCAPTCHA/blob/master/_docs/5-Usage.md#laravel).
