### ISSUE TITLE
reload

### ISSUE THREAD

**Issue by jeffagostinho** [ARCANEDEV/noCAPTCHA#42]
Good night,

I'm sending my form via ajax, is there any way I can update the captcha?

Thank you

**Comment by arcanedev-maroc** [comment]
What do you mean by "update the captcha" ?

**Comment by jeffagostinho** [comment]
Sorry friend,

My problem was as follows, when posting with ajax was giving captcha error because it was not being updated.

But it was only to use grecaptcha.reset ();

excuse

**Comment by arcanedev-maroc** [comment]
No problem 👍

Feel free to post any issue encountered/related to this package.

Best regards
