### ISSUE TITLE
Method [validateCaptcha] does not exist

### ISSUE THREAD

**Issue by ivanvermeyen** [ARCANEDEV/noCAPTCHA#44]
Hey

After updating your package from 3.1.0 to 3.2.0 Laravel throws this exception after submitting a form:

```
BadMethodCallException in Validator.php line 3388:
Method [validateCaptcha] does not exist.
```

I'm using Laravel 5.3.
Couldn't really figure out yet what goes wrong exactly...

**Comment by arcanedev-maroc** [comment]
I know because the service provider is deferred.

Sorry about that, i'm going to fix that.

**Comment by ivanvermeyen** [comment]
Thanks for the quick fix ! 👍
