### ISSUE TITLE
Fails to display google images

### ISSUE THREAD

**Issue by da40** [ARCANEDEV/noCAPTCHA#46]
Clicking on the "I'm not a robot" button causes the "waiting" cursor to appear, but nothing else happens.  This is after following the installation instructions for a Laravel 5.2 application.

**Comment by arcanedev-maroc** [comment]
Are you sure this is related to this package or something else (like javascript or google captcha itself)?

**Comment by da40** [comment]
I switched to this from anhskohbo/no-captcha, because it stopped working with the same symptoms.  It turned out to be because I had put square brackets around the values assigned to NOCAPTCHA_SECRET and NOCAPTCHA_SITEKEY, as per its documentation.  Deleting those solved the problem for both that version and this.  As you can see on the anhskohbo issues page, several other people had this problem, so I guess google must have changed their javascript.

Having now discovered your implementation, I'll stick with it as it handles the additional attributes, thanks.

**Comment by arcanedev-maroc** [comment]
@DA40 can you give us the issue link of the `anhskohbo/no-captcha` package ?

**Comment by da40** [comment]
https://github.com/anhskohbo/no-captcha/issues/56

**Comment by arcanedev-maroc** [comment]
Thanks 👍
