### ISSUE TITLE
Error on composer require

### ISSUE THREAD

**Issue by stefensuhat** [ARCANEDEV/noCAPTCHA#48]
- noCaptcha Version: Latest
- Laravel Version: 5.4.12
- PHP Version: 7.1

### Description:
Error on first installation

### Steps To Reproduce:
composer require arcanedev/no-captcha

  Problem 1
    - Conclusion: don't install arcanedev/no-captcha 3.2.1
    - Conclusion: remove arcanedev/support 4.1.4
    - Installation request for arcanedev/no-captcha ^3.2 -> satisfiable by arcanedev/no-captcha[3.2.0, 3.2.1].
    - Conclusion: don't install arcanedev/support 4.1.4
    - arcanedev/no-captcha 3.2.0 requires arcanedev/support ~3.20 -> satisfiable by arcanedev/support[3.20.0, 3.20.1, 3.20.2, 3.20.3, 3.21.0, 3.21.1, 3.21.2, 3.21.3].
    - Can only install one of: arcanedev/support[3.20.0, 4.1.4].
    - Can only install one of: arcanedev/support[3.20.1, 4.1.4].
    - Can only install one of: arcanedev/support[3.20.2, 4.1.4].
    - Can only install one of: arcanedev/support[3.20.3, 4.1.4].
    - Can only install one of: arcanedev/support[3.21.0, 4.1.4].
    - Can only install one of: arcanedev/support[3.21.1, 4.1.4].
    - Can only install one of: arcanedev/support[3.21.2, 4.1.4].
    - Can only install one of: arcanedev/support[3.21.3, 4.1.4].
    - Installation request for arcanedev/support (locked at 4.1.4) -> satisfiable by arcanedev/support[4.1.4].

**Comment by arcanedev-maroc** [comment]
Fixed: #49
