### ISSUE TITLE
invisible Recaptcha support?

### ISSUE THREAD

**Issue by chrisbbreuer** [ARCANEDEV/noCAPTCHA#50]
Hi!

I like this package and was wondering if you think about including the new invisible Recaptcha?

**Comment by ivanvermeyen** [comment]
That would be cool.
Just FYI, I already got it to work with this package, by adding the script and the HTML myself:

```html
<button type="submit"
        class="g-recaptcha"
        data-sitekey="{{ config('no-captcha.sitekey') }}"
        data-callback="sendForm"
        data-badge="inline">
    Send
</button>

<script src='https://www.google.com/recaptcha/api.js'></script>
```

Then just create your `sendForm` function to submit the form manually and let this package handle the backend validation :)

**Comment by arcanedev-maroc** [comment]
The invisible recaptcha is going to be supported in the next release.

See PR: #51 

So the new method to render the invisible recaptcha is by calling the `button($value, array $attributes = [])` method.

```php
<?php

require_once "vendor/autoload.php";

use Arcanedev\NoCaptcha\NoCaptcha;

$secret  = 'secret-key';
$sitekey = 'site-key';
$captcha = new NoCaptcha($secret, $sitekey);

if ( ! empty($_POST)) {
    $response = $_POST[NoCaptcha::CAPTCHA_NAME];
    $result   = $captcha->verify($response);

    echo $result === true ? 'Yay ! You are a human.' : 'No ! You are a robot.';

    exit();
}
?>

<form method="POST" id="demo-form">
    <?php echo $captcha->button('Send', ['data-badge' => 'inline']); ?>
</form>

<?php echo $captcha->script(); ?>


<script>
    function onSubmit(token) {
        document.getElementById("demo-form").submit();
    }
</script>
```

The default recaptcha's callback is `onSubmit` for invisible version, you can customize it like this:

```php
$captcha->button('Send', ['data-callback' => 'sendForm', 'data-badge' => 'inline']);
```

Check the documentation for more details about the usage.

**Comment by arcanedev-maroc** [comment]
Released as `4.0.1`

**Comment by bumTomica** [comment]
@arcanedev-maroc Add support in 3.* versions too?

**Comment by arcanedev-maroc** [comment]
Sorry @bumTomica, but the version "3.*" is closed for any new features (only bug fixes).
