### ISSUE TITLE
no longer support laravel 4.2

### ISSUE THREAD

**Issue by dwenaus** [ARCANEDEV/noCAPTCHA#52]
- noCaptcha Version: #.#.#
- Laravel Version: #.#.# 4.2
- PHP Version: #.#.# 5.5

### Description:
won't install via composer because arcanedev/support requires illuminate v5

**Comment by arcanedev-maroc** [comment]
Check the documentation: https://github.com/ARCANEDEV/noCAPTCHA/blob/master/_docs/1-Installation-and-Setup.md#version-compatibility
