### ISSUE TITLE
Laravel invisible ex

### ISSUE THREAD

**Issue by zKoz210** [ARCANEDEV/noCAPTCHA#53]
- noCaptcha Version: latest
- Laravel Version: 5.4.21
- PHP Version: 7.1.0

### Description:
Please add example invisible re-captcha for Laravel, thanks!

**Comment by arcanedev-maroc** [comment]
Here you go: https://github.com/ARCANEDEV/noCAPTCHA/blob/master/_docs/3-Usage.md#invisible-captcha

**Comment by zKoz210** [comment]
I really don't know how to do it in Laravel...

Example form

```blade
<form id="loginForm" action="{{ route('auth.login') }}" method="POST">
    {!! csrf_field() !!}

    <div class="form-group has-feedback">
        <input name="user" class="form-control" value="{{ old('user') }}" placeholder="@lang('strings.user_identifier')">
        <span class="fa fa-envelope form-control-feedback"></span>
    </div>
    <div class="form-group has-feedback">
        <input type="password" name="password" class="form-control" placeholder="@lang('strings.password')">
        <span class="fa fa-lock form-control-feedback"></span>
    </div>
    {!! Captcha::display() !!}
    <div class="row">
        <div class="col-xs-4">
            <button type="submit" class="btn btn-primary btn-block btn-flat">@lang('auth.sign_in')</button>
        </div>
    </div>
</form>
```

**Comment by arcanedev-maroc** [comment]
Use `Captcha::button('Send', ['data-badge' => 'inline'])` instead of `Captcha::display()`.

And the bottom :

```blade
{!! $captcha->script() !!}
<script>
    function onSubmit(token) {
        document.getElementById("loginForm").submit();
    }
</script>
```

**Comment by zKoz210** [comment]
Thank you very much!

**Comment by zKoz210** [comment]
![image](https://cloud.githubusercontent.com/assets/28255085/25579180/1891a9ee-2e7e-11e7-8972-23726bba0e2a.png)

Hmm..

```
    protected function validateLogin(Request $request)
    {
        $this->validate($request, [
            $this->username() => 'required|string',
            'password' => 'required|string',
            'g-recaptcha-response' => ['required', 'captcha'],
        ]);
    }
```

![image](https://cloud.githubusercontent.com/assets/28255085/25579200/4621097c-2e7e-11e7-9271-f53a8ba15d1a.png)
![image](https://cloud.githubusercontent.com/assets/28255085/25579202/4d0512f6-2e7e-11e7-9692-6e1b4d5e7ecc.png)


How can I fill the invisible captcha?

**Comment by arcanedev-maroc** [comment]
Can you try to set the captcha name ?

```blade
{!! Captcha::button(trans('auth.sign_in'), ['name' => 'g-recaptcha-response', 'class' => '...']) !!}
```

And to check your inputs:

```php
protected function validateLogin(Request $request)
{
    dd($request->all());  // Check that you get all the inputs including the 'g-recaptcha-response'

    $this->validate($request, [
        $this->username() => 'required|string',
        'password' => 'required|string',
        'g-recaptcha-response' => ['required', 'captcha'],
    ]);
}
```

**Comment by zKoz210** [comment]
```
array:4 [▼
  "_token" => "naL27bhOuk9HH8dbzg8UWV3pXWVG4DGyatKSWcoZ"
  "user" => "zKoz210"
  "password" => "MyPassword"
  "g-recaptcha-response" => ""
]
```

![image](https://cloud.githubusercontent.com/assets/28255085/25579777/7450c22e-2e83-11e7-9e34-9bca9e7d49e6.png)

**Comment by arcanedev-maroc** [comment]
Are you sending the form with ajax ?

**Comment by zKoz210** [comment]
No, default auth from Laravel

**Comment by arcanedev-maroc** [comment]
Ok, i'm going to check this and see if i can reproduce your issue.

**Comment by zKoz210** [comment]
Okay, thanks!

**Comment by arcanedev-maroc** [comment]
OK, i see the issue, if you want to apply custom css class, you can do it but you need to keep the default recaptcha class, try something like this:

```blade
{!! Captcha::button(trans('auth.sign_in'), ['class' => 'g-recaptcha btn btn-primary btn-block btn-flat']) !!}
```

You can check the official documentation for more details: https://developers.google.com/recaptcha/docs/invisible

**Comment by Pub4Game** [comment]
@arcanedev-maroc You are great! Thank you very much for this packet. It helped me too!

**Comment by arcanedev-maroc** [comment]
You're welcome @Pub4Game 👍

**Comment by zKoz210** [comment]
@arcanedev-maroc @Pub4Game Yes. Thanks.
