### ISSUE TITLE
NoCaptcha is slave labor. Stop helping Google commit evil.

### ISSUE THREAD

**Issue by simbalion** [ARCANEDEV/noCAPTCHA#55]
Google's "NoCaptcha ReCaptcha" product is slave labor. It is illegal, and it needs to be stopped.

Google is using this system to force millions of Americans and foreigners to "tag" their massive database of photographs without any form of compensation. This has been going on for years and it needs to stop.

The system presents a user with a series of photographs and asks the user to identify which photographs contain specific key elements such as cars, street signs, store fronts, and so on. If the user doesn't cooperate they cannot continue their internet activity. This is a clear violation of both the spirit and letter of United States labor laws.

Here is a link to my personal blog post on the issue:
https://tailpuff.net/googles-nocaptcha-recaptcha-is-slave-labor/

**Comment by ivanvermeyen** [comment]
Interesting point of view... I think that not using any captcha would be more user friendly. But spammers would love that, so I'm afraid we don't have a choice. Although there are other captcha solutions out there, the one from Google does appear to have the least impact on the user. Especially with the invisible captcha, they might not even notice it's there. What alternatives would you suggest?

As always with companies like Google there is this ongoing struggle between privacy and convenience. Your story seems to be another layer in this struggle. As with any service, until I find a better or equally good alternative, I'm sticking with the best option available...

**Comment by simbalion** [comment]
In my opinion the best methods don't use a captcha at all. Take a look at https://wordpress.org/plugins/goodbye-captcha/ and http://nomorecaptchas.com/, they both offer free options (the second has a tiered payment system based on number of visitors/verifications).

I can't speak for the second one, but the first I've been using for a couple of years now and it is 100% effective in blocking comment form bot spam where I have it installed. I have replaced captchas with it on every website I manage. Obviously that particular solution only works with WordPress but I am certain that the method it uses could be adapted to other platforms and purposes.

This is both the most user friendly approach, and avoids feeding the google machine, which only a few years ago was just "slightly worrisome", but today it is truly hideous, a real life "big brother". They tried to get rid of top level domains so they could own the internet domain "search" and then they changed their company name to "Alphabet", I mean seriously they need to be stopped. If you check the technology news today they just got fined 2.4 _billion_ euros for using their search engine to promote their own links in the shopping comparison results. Disgusting.
