### ISSUE TITLE
Multiple Laravel 5.4.26 reCaptcha

### ISSUE THREAD

**Issue by lordrost** [ARCANEDEV/noCAPTCHA#57]
- noCaptcha Version: 4.0.1
- Laravel Version: 5.4.26
- PHP Version: 7.1.5

### Description:

I'm trying to implement 2 reCaptcha on the same page of my laravel project. 

I'm using your code from FAQ

```
{{ Form::open(['method' => 'POST'])}}
    {{ Form::captcha(['id' => 'captcha1']) }}
    {{ Form::submit('Submit form 1')}}
{{ Form::close() }}

{{ Form::open(['method' => 'POST']) }}
    {{ Form::captcha(['id' => 'captcha2')] }}
    {{ Form::submit('Submit form 2')}}
{{ Form::close() }}

{{ Captcha::scriptWithCallback(['captcha1', 'captcha2']) }}
```

And i got 

> trim() expects parameter 1 to be string, array given (View: /var/www/html/resources/views

### Steps To Reproduce:

Use `{{ Form::captcha(['id' => 'captcha2')] }}` in Laravel Project

**Comment by arcanedev-maroc** [comment]
It's `{{ Form::captcha('captcha2') }}` instead of `{{ Form::captcha(['id' => 'captcha2']) }}`.

You're passing an *array* instead of *string*.
