### ISSUE TITLE
Could you update this plugin for Laravel 5.5?

### ISSUE THREAD

**Issue by naviace** [ARCANEDEV/noCAPTCHA#59]
- noCaptcha Version: latest
- Laravel Version: 5.5.0
- PHP Version: 7.1.8

Could you update this plugin for Laravel 5.5?

**Comment by arcanedev-maroc** [comment]
I'm going to update this package after updating the *core dependencies* first like `arcanedev/support`.

👍

**Comment by arcanedev-maroc** [comment]
**PR:** #60
