### ISSUE TITLE
Trouble with Form macro in Laravel 5.5

### ISSUE THREAD

**Issue by rappasoft** [ARCANEDEV/noCAPTCHA#61]
- noCaptcha Version: 5.0
- Laravel Version: 5.5.3
- PHP Version: 7.1

### Description:

Trying to use Form::captcha() with error.

### Steps To Reproduce:

Set up captcha with Form::captcha() instead of Captcha::display()

---

I have this in one other Laravel 5.4 projects without issue.

The problem lies in **Arcanedev\NoCaptcha\NoCaptchaServiceProvider**

Trying to import **Arcanedev\LaravelHtml\Contracts\FormBuilder** and not being able to find it.

Also, using Captcha::display() doesn't break the page, but it also doesn't display the actual captcha, though the div does exist.

**Comment by arcanedev-maroc** [comment]
Which package you're using to generates forms/inputs ?

 1. `arcanedev/laravel-html`
 2. `laravelcollective/html`

These are the changes applied for Laravel 5.5: https://github.com/ARCANEDEV/noCAPTCHA/commit/d2abb1e39d8f8169eaf1787be82424db4298c257#diff-246317e07890ff584fd40052cb7315b8L107

**Comment by rappasoft** [comment]
2 like I always have been.

**Comment by arcanedev-maroc** [comment]
Ok, you can add this code in your `AppServiceProvider@boot()` to solve this issue:

```php
if ($app->bound('form')) {
    $app['form']->macro('captcha', function($name = null, array $attributes = []) use ($app) {
        return $app[\Arcanedev\NoCaptcha\Contracts\NoCaptcha::class]->display($name, $attributes);
    });
}
```

**Comment by rappasoft** [comment]
Would there be a more elegant way? My current project has this implemented along with laravelcollective and it works great.

**Comment by arcanedev-maroc** [comment]
Ok i see the issue, in my `laravel-html` package (it's similar to Laravel & laravelcollective `html/form` features), it has the same `alias` as the others.

But in Laravel 5.5, i dropped the name `form` for the binding and used a contract instead `Arcanedev\LaravelHtml\Contracts\FormBuilder`, this is what breaks your app.

**Comment by rappasoft** [comment]
This is for http://github.com/rappasoft/laravel-5-boilerplate

Which your log viewer and captcha are currently part of, I'd like to keep them in there.

Let me know if you find a solution.

**Comment by arcanedev-maroc** [comment]
Check if the PR solves the issue

**Comment by arcanedev-maroc** [comment]
Solved, try to update the package to `v5.0.1`

**Comment by rappasoft** [comment]
Ok that fixed the error, but is it set to invisible by default? I cant get it to display with either helper, though the html is there in the source.

**Edit: Disregard thats on my end.**

**Comment by arcanedev-maroc** [comment]
No, the default is the regular captcha (`Captcha::display() === Form::captcha()`).

The invisible one is `Captcha::button()`, check [this section](https://github.com/ARCANEDEV/noCAPTCHA/blob/master/_docs/3-Usage.md#invisible-captcha) for more details.

**Comment by rappasoft** [comment]
Yeah it works now my scripts stack had a typo, thanks a lot!
