### ISSUE TITLE
Issues with Controller validation, Laravel 4.2 (fix included)

### ISSUE THREAD

**Issue by ashikai** [ARCANEDEV/noCAPTCHA#63]
- noCaptcha Version: 1.2.7
- Laravel Version: 4.2
- PHP Version: 5

### Description:

I followed the steps in the instruction only to receive errors; you can't use "use Arcanedev/etc" (the 'use' command throws the error, not the path name), and the line
`'g-recaptcha-response' => ['required', new CaptchaRule]`
should really be
`'g-recaptcha-response' => 'required|captcha',` or else you get an error as well (CaptchaRule is invalid/undefined variable).
Also found that for some reason a `return false;` and `return true;` is required on the validation check or else it will always return false.

I'm not sure if anyone else is having this issue at all, but after a lot of debugging I found a solution that works for me. I just wanted to share this and maybe ArcaneDev can shed a little light on to why this is the case. If not, that's cool. It's working now, so I'm good. 

### Original Code from the installation manual:

```php
use Arcanedev\NoCaptcha\Rules\CaptchaRule;

$validator = Validator::make(Input::all(), [
    'g-recaptcha-response' => ['required', new CaptchaRule],
]);

if ($validator->fails()) {
    $errors = $validator->messages();
    var_dump($errors->first('g-recaptcha-response'));
}
```

### Current Working Solution:

```php
$validator = Validator::make(Input::all(), [
    // Other validation rules...
    'g-recaptcha-response' => 'required|captcha',
]);
if ($validator->fails()) {
    $errors = $validator->messages();
    return false;
}
else{
    return true;
}
```

(removed the `var_dump` from this one because it causes the screen to flash with the error message before properly reloading)

**Comment by arcanedev-maroc** [comment]
Check [this section](https://github.com/ARCANEDEV/noCAPTCHA/blob/master/_docs/1-Installation-and-Setup.md#version-compatibility).

If you're using Laravel `v4.2`, switch to old branch/tag.

The new `CaptchaRule` class is only for Laravel `>= v5.5`.
