### ISSUE TITLE
Interface 'Illuminate\Contracts\Validation\Rule' not found

### ISSUE THREAD

**Issue by visualight** [ARCANEDEV/noCAPTCHA#64]
- noCaptcha Version: ^5.0
- Laravel Version: 5.4.35
- PHP Version: 7.0.22

### Description:
Error on validation
`Interface 'Illuminate\Contracts\Validation\Rule' not found - in CaptchaRule.php (line 12)`

### Steps To Reproduce:
Create a validatorRequest File in request directory and use the following rule : 
`use Arcanedev\NoCaptcha\Rules\CaptchaRule;`

```php
public function rules()
{
    $rules = [
        'name' => 'required',
        'email' => 'required|email',
        'message' => 'required',
        'g-recaptcha-response' => ['required', new CaptchaRule],
    ];

    return $rules;
}
```

Processing : 

```php
public function sendmail(ValidatorRequest $request)
{
    $data = $request->all();
    dd($data);
}
```

**Comment by tehwave** [comment]
CaptchaRule implements Rule, which was introduced in Laravel 5.5.

**Comment by visualight** [comment]
How to work with Laravel 5.4 ?

**Comment by tehwave** [comment]
Use release version 4.0.1

https://github.com/ARCANEDEV/noCAPTCHA/releases/tag/4.0.1

**Comment by arcanedev-maroc** [comment]
Downgrade your version to `~4.0`

Related: https://github.com/ARCANEDEV/noCAPTCHA/issues/63
