### ISSUE TITLE
Method [validateCaptcha] does not exist.

### ISSUE THREAD

**Issue by rwnet** [ARCANEDEV/noCAPTCHA#67]
- noCaptcha Version: 5.0.1
- Laravel Version: 5.5.32
- PHP Version: 7.1.9

Hello.

Installed everything according to the documentation, but there is an error "Method [validateCaptcha] does not exist" after submitting form. I'm trying to use recaptcha on Laravel default generated login form.

Couldn't figure out yet what goes wrong exactly...

Tried to manually describe service providers and alias - nothing changed.

**Comment by arcanedev-maroc** [comment]
For the latest release, use the new `Rule` class instead of `'captcha'` rule for validation:

```php
use Arcanedev\NoCaptcha\Rules\CaptchaRule;

$validator = Validator::make(request()->all(), [
    // Other validation rules...
    'g-recaptcha-response' => ['required', new CaptchaRule],
]);
```

**Comment by rwnet** [comment]
Thank you. Now everything has worked for me!
