### ISSUE TITLE
Laravel 5 Support

### ISSUE THREAD

**Issue by stevebauman** [ARCANEDEV/noCAPTCHA#7]
Hi, I'm just wondering if Laravel 5 support is in the works? You can make it backwards compatible with Laravel 4 as well, as I've done this myself.

**Comment by arcanedev-maroc** [comment]
For laravel 5.0: #9 
Can you please specify the backwards versions of laravel because this package works perfectly with laravel 4.2.x.

Tnx for the feedback ( ^_^)b

**Comment by stevebauman** [comment]
Awesome!! Thanks for this, really appreciate it.
