### ISSUE TITLE
Always getting language from config app.locale

### ISSUE THREAD

**Issue by gsgarin** [ARCANEDEV/noCAPTCHA#71]
- noCaptcha Version: 5.0.2
- Laravel Version: 5.5.39 
- PHP Version: 7.2.3

I'm using https://github.com/mcamara/laravel-localization to manage multi locale. But, it won't change when locale has change to another language. 
In my config: no-captcha.php
    'lang'    => app()->getLocale(),
It always getting default locale from app.php, it should get new updated locale.
How to fix it?

**Comment by arcanedev-maroc** [comment]
Try to change the locale in the `AppServiceProvider`:

```php
public function boot()
{
    config(['no-captcha.lang' => app()->getLocale()]); 
    // Or use your localization package to get the selected locale
}
```

Or:

```php
use ARCANEDEV\noCAPTCHA\Contracts\NoCaptcha as NoCaptchaContract;

//...

$this->app->resolving(NoCaptchaContract::class, function (NoCaptchaContract $noCaptcha, $app) {
    /** @var  \Illuminate\Foundation\Application  $app */
    $noCaptcha->setLang($app->getLocale());
});
```
