### ISSUE TITLE
Hope added DOMAIN config.

### ISSUE THREAD

**Issue by shar0** [ARCANEDEV/noCAPTCHA#72]
I'm use Laravel in China.
`Google.com` has been blocked, but `reCAPTCHA.net` not.
Can add a config options for specific reCAPTCHA server domain?

**Comment by arcanedev-maroc** [comment]
I don't know what to say because this package only supports the official reCAPTCHA server.

You can make a PR but it's going to be in future release because it's a breaking change feature.

**NOTE:** http://recaptcha.net doesn't work for me
