### ISSUE TITLE
Class 'Captcha' not found in login.blade

### ISSUE THREAD

**Issue by rwnet** [ARCANEDEV/noCAPTCHA#73]
- noCaptcha Version: 6.0.1
- Laravel Version: 5.6.17
- PHP Version: 7.2.0

Hi. After the upgrade from version 5 to version 6, invisible captcha ceased to work. In my login.blade I use it like this
`{!! Captcha::button('Sign In', ['name' => 'g-recaptcha-response', 'class' => 'g-recaptcha btn btn-primary']) !!}`

When I open the login page, I get this error "Class 'Captcha' not found". I did not find any release notes that would help me solve the problem.

**Comment by Gummibeer** [comment]
To use `Captcha` you have to add the alias to your app config.
https://github.com/ARCANEDEV/noCAPTCHA/blob/master/_docs/1-Installation-and-Setup.md
