### ISSUE TITLE
Laravel 4.2 CaptchaRule

### ISSUE THREAD

**Issue by ligoo** [ARCANEDEV/noCAPTCHA#77]
- noCaptcha Version: 1.2.7
- Laravel Version: 4.2.22
- PHP Version: 5.6.37

### Description: Can't get Laravel to recognize the CaptchaRule.

Got this error: "Class 'Arcanedev\NoCaptcha\Rules\CaptchaRule' not found" on the `use Arcanedev\NoCaptcha\Rules\CaptchaRule;`

Does the namespace has changed from 4.2 ?

**Comment by ligoo** [comment]
Seems the answer is somewhere here: https://github.com/ARCANEDEV/noCAPTCHA/issues/63

Maybe you should clarify the documentation about this for laravel 4.2.

**Comment by arcanedev-maroc** [comment]
I don't think it's necessary because the **Rule Objects** are introduced in laravel v5.5

CHANGELOG v5.5: https://github.com/laravel/framework/blob/5.5/CHANGELOG-5.5.md#validation
Documentation: https://laravel.com/docs/5.5/validation#using-rule-objects
