### ISSUE TITLE
Problem with using V2 driver

### ISSUE THREAD

**Issue by rwnet** [ARCANEDEV/noCAPTCHA#83]
- noCaptcha Version: 8.0.2
- Laravel Version: 5.7.24
- PHP Version: 7.1.22

### Description:
Is it right to initialize V3 driver instead of V2 here?

https://github.com/ARCANEDEV/noCAPTCHA/blob/cbef775f98be11199d5b953603b922db3fa3d116/src/NoCaptchaManager.php#L49-L56

### Steps To Reproduce:
It's simple to reproduce, just use `{!! no_captcha('v2')->display() !!}`  in blade template and you get an error that NoCapthcaV3 doesn't have display() method.

**Comment by arcanedev-maroc** [comment]
My bad :stuck_out_tongue_closed_eyes: 

Try to update the package to `v8.0.3`.

BTW, you can use `{{ no_captcha('v2')->display() }}` without `{!! ... !!}`

Thanks for the feedback :+1:

**Comment by rwnet** [comment]
Thanks a lot!
