### ISSUE TITLE
reCAPTCHA v3 not working

### ISSUE THREAD

**Issue by Morinohtar** [ARCANEDEV/noCAPTCHA#88]
- noCaptcha Version: 9.x
- Laravel Version: 5.8.x
- PHP Version: 7.3.x

### Description:

First issue:
The `{!! no_captcha()->display() !!}` does not work, because the `display` method is not present in the NoCaptchaV3 class. We have to use the `input` method.

Second issue:
When using the `{!! no_captcha()->display() !!}` it does not show the captcha and doesnt show any error. When i inspect the html i can only see the input: `<input type="hidden" id="g-recaptcha-response" name="g-recaptcha-response">`

What might be causing this? Thanks.

**Comment by arcanedev-maroc** [comment]
Check the example for the `reCAPTCHA V3`: 
https://github.com/ARCANEDEV/noCAPTCHA/blob/master/examples/v3/simple.php
