### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by KumaChenGC** [ARCANEDEV/noCAPTCHA#93]
Problem 1
    - Installation request for arcanedev/no-captcha ^10.1 -> satisfiable by arcanedev/no-captcha[10.1.0].
    - Conclusion: remove laravel/framework v5.7.28
    - Conclusion: don't install laravel/framework v5.7.28
    - arcanedev/no-captcha 10.1.0 requires arcanedev/support ^5.0 -> satisfiable by arcanedev/support[5.0.0, 5.1.0, 5.1.1].
    - arcanedev/support 5.1.0 requires illuminate/support ^6.0 -> satisfiable by laravel/framework[6.x-dev], illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0].
    - arcanedev/support 5.1.1 requires illuminate/support ^6.0 -> satisfiable by laravel/framework[6.x-dev], illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0].
    - arcanedev/support 5.0.0 requires illuminate/filesystem ~6.0.0 -> satisfiable by illuminate/filesystem[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4].
    - Can only install one of: laravel/framework[6.x-dev, v5.7.28].
    - don't install illuminate/support 6.x-dev|don't install laravel/framework v5.7.28
    - don't install illuminate/support v6.0.0|don't install laravel/framework v5.7.28
    - don't install illuminate/support v6.0.1|don't install laravel/framework v5.7.28
    - don't install illuminate/support v6.0.2|don't install laravel/framework v5.7.28
    - don't install illuminate/support v6.0.3|don't install laravel/framework v5.7.28
    - don't install illuminate/support v6.0.4|don't install laravel/framework v5.7.28
    - don't install illuminate/support v6.1.0|don't install laravel/framework v5.7.28
    - don't install illuminate/support v6.2.0|don't install laravel/framework v5.7.28
    - don't install illuminate/support v6.3.0|don't install laravel/framework v5.7.28
    - don't install illuminate/support v6.4.1|don't install laravel/framework v5.7.28
    - don't install illuminate/support v6.5.0|don't install laravel/framework v5.7.28
    - don't install illuminate/support v6.5.1|don't install laravel/framework v5.7.28
    - don't install illuminate/support v6.5.2|don't install laravel/framework v5.7.28
    - don't install illuminate/support v6.6.0|don't install laravel/framework v5.7.28
    - don't install illuminate/filesystem v6.0.0|don't install laravel/framework v5.7.28
    - don't install illuminate/filesystem v6.0.1|don't install laravel/framework v5.7.28
    - don't install illuminate/filesystem v6.0.2|don't install laravel/framework v5.7.28
    - don't install illuminate/filesystem v6.0.3|don't install laravel/framework v5.7.28
    - don't install illuminate/filesystem v6.0.4|don't install laravel/framework v5.7.28
    - Installation request for laravel/framework == 5.7.28.0 -> satisfiable by laravel/framework[v5.7.28].

**Comment by KumaChenGC** [comment]
Solved, cause my laravel is 5.7 and i install no-captcha 10.x .

**Comment by arcanedev-maroc** [comment]
Duplicated: #56
