### ISSUE TITLE
Help me to upgrade into recaptcha v3

### ISSUE THREAD

**Issue by ghost** [ARCANEDEV/noCAPTCHA#96]
- noCaptcha Version: 9.0.0
- Laravel Version: 5.8.38
- PHP Version: 7.2.31

I used "anhskohbo/no-captcha": "^3.0" in v2 and it doesnt support v3 so now I want to upgrade into v3 by using this package.

I am using blade syntax and had a look issue #90 but I can see nothing on my fronend.

Thanks in advance.

**Comment by arcanedev-maroc** [comment]
Just follow the example: https://github.com/ARCANEDEV/noCAPTCHA/issues/90#issuecomment-498075504
