### ISSUE TITLE
Request: Captcha version in a env variable

### ISSUE THREAD

**Issue by ebelendez** [ARCANEDEV/noCAPTCHA#98]
- noCaptcha Version: 3.#.#
- Laravel Version: 7.#.#
- PHP Version: 7.#.#

### Description: Hi, I would like that my users could choose between captcha v2 and v3 without publishing the config file. ¿do you think it is possible to include it as an env variable? NOCAPTCHA_VERSION

Thanks

**Comment by arcanedev-maroc** [comment]
You can change the config value without publishing the config file by using `config(['no-captcha.version' => 'v2']);` at application's runtime

Check: https://laravel.com/docs/7.x/helpers#method-config

**Note:** The ENV variable is used for your application not for the users.
